# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 11:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('sex', models.CharField(blank=True, max_length=128, null=True)),
                ('image', models.CharField(default='http://images.uncyc.org/zh-tw/3/32/Nobody%E9%A0%AD%E5%83%8F.jpg', max_length=128)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('lavel', models.FloatField()),
                ('emailVerifyCode', models.CharField(max_length=128)),
                ('isEmailVerified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
